// AG-specific public copy and the new inbox/editor labels in every supported language.
const keys = ['home.title', 'home.description', 'home.products', 'home.productsText', 'home.aboutText', 'home.contactText', 'feedback.all', 'feedback.empty', 'editor.basics', 'editor.release'];
const rows = {
en: 'Everything AG, in one place.|Explore AG products, learn about AG and get in touch. Welcome to our home on the web.|Explore AG products|Discover our software and apps, with links for the platforms you use.|Get to know AG and the ideas behind our work.|Have a question, an idea or feedback? We would like to hear from you.|All|No messages in this filter.|Product information|Version & status',
ur: 'AG کی دنیا، ایک ہی جگہ۔|AG کی مصنوعات دریافت کریں، ہمارے بارے میں جانیں اور ہم سے رابطہ کریں۔ ہماری ہوم سائٹ پر خوش آمدید۔|AG کی مصنوعات دریافت کریں|ہمارے سافٹ ویئر اور ایپس دیکھیں، اپنے پلیٹ فارم کے لیے درست لنک کے ساتھ۔|AG اور ہمارے کام کے پیچھے موجود خیالات کے بارے میں جانیں۔|سوال، تجویز یا رائے ہے؟ ہمیں اپنا پیغام بھیجیں۔|سب|اس فلٹر میں کوئی پیغام نہیں۔|پروڈکٹ کی معلومات|ورژن اور حالت',
ar: 'كل ما يخص AG، في مكان واحد.|اكتشف منتجات AG وتعرّف علينا وتواصل معنا. مرحباً بك في موقعنا.|اكتشف منتجات AG|تصفح برامجنا وتطبيقاتنا مع روابط للمنصات التي تستخدمها.|تعرّف على AG والأفكار وراء عملنا.|لديك سؤال أو فكرة أو ملاحظة؟ يسعدنا سماعك.|الكل|لا توجد رسائل ضمن هذا المرشح.|معلومات المنتج|الإصدار والحالة',
tr: 'AG ile ilgili her şey, tek yerde.|AG ürünlerini keşfedin, bizi tanıyın ve iletişime geçin. Web sitemize hoş geldiniz.|AG ürünlerini keşfedin|Kullandığınız platformlara ait bağlantılarla yazılım ve uygulamalarımızı keşfedin.|AG ve çalışmalarımızın arkasındaki fikirleri tanıyın.|Sorunuz, fikriniz veya görüşünüz mü var? Sizden haber almak isteriz.|Tümü|Bu filtrede mesaj yok.|Ürün bilgileri|Sürüm ve durum',
ja: 'AGのすべてを、ひとつの場所で。|AGの製品を探し、私たちについて知り、お問い合わせください。ようこそ。|AGの製品を探す|お使いのプラットフォームへのリンクとともに、ソフトウェアやアプリをご覧ください。|AGと、私たちの仕事の背景にあるアイデアを知る。|質問、アイデア、ご意見があればお聞かせください。|すべて|この条件のメッセージはありません。|製品情報|バージョンと状態',
zh: '关于 AG 的一切，尽在这里。|探索 AG 产品，了解我们并联系我们。欢迎来到我们的主页。|探索 AG 产品|浏览我们的软件和应用，获取适合您平台的链接。|了解 AG 及我们工作的理念。|有问题、想法或反馈？欢迎告诉我们。|全部|此筛选下没有消息。|产品信息|版本与状态',
pa: 'AG دی دنیا، اکّو تھاں۔|AG دیاں مصنوعات ویکھو، ساڈے بارے جانو تے رابطہ کرو۔ ساڈی ہوم سائٹ تے جی آیاں نوں۔|AG دیاں مصنوعات ویکھو|ساڈے سافٹ ویئر تے ایپس اپنے پلیٹ فارم دے لنک نال ویکھو۔|AG تے ساڈے کم پچھے دے خیالاں بارے جانو۔|سوال، تجویز یا رائے اے؟ سانوں پیغام بھیجو۔|سارے|ایس فلٹر وچ کوئی پیغام نئیں۔|پروڈکٹ دی معلومات|ورژن تے حالت',
ps: 'د AG هر څه، په یوه ځای کې.|د AG محصولات وګورئ، زموږ په اړه پوه شئ او اړیکه ونیسئ. زموږ وېبپاڼې ته ښه راغلاست.|د AG محصولات وګورئ|زموږ سافټویر او اپلېکېشنونه د خپلو پلاتفورمونو له لینکونو سره وګورئ.|د AG او زموږ د کار د نظریو په اړه پوه شئ.|پوښتنه، نظر یا وړاندیز لرئ؟ پیغام راولېږئ.|ټول|په دې فلټر کې پیغام نشته.|د محصول معلومات|نسخه او حالت',
bal: 'AG ءِ دنیا، یک جاگہ ءَ۔|AG ءِ مصنوعات ببین، ما ءِ باروا بزان ءُ رابطہ بکن۔ ما ءِ ہوم سائٹ ءَ وش آتکے۔|AG ءِ مصنوعات ببین|ما ءِ سافٹ ویئر ءُ ایپاں وتی پلیٹ فارم ءِ لنک ءَ ببین۔|AG ءُ ما ءِ کار ءِ خیالاں ءِ باروا بزان۔|سوال، خیال یا رائے ہست؟ ما ءَ پیغام بدے۔|گشت|اے فلٹر ءَ پیغام نیست۔|پروڈکٹ ءِ معلومات|ورژن ءُ حالت',
fr: 'Tout AG, au même endroit.|Découvrez les produits AG, notre univers et contactez-nous. Bienvenue sur notre site.|Découvrez les produits AG|Explorez nos logiciels et applications avec les liens adaptés à vos plateformes.|Découvrez AG et les idées qui inspirent notre travail.|Une question, une idée ou un avis ? Écrivez-nous.|Tous|Aucun message pour ce filtre.|Informations du produit|Version et statut',
es: 'Todo AG, en un solo lugar.|Descubre los productos AG, conoce nuestro trabajo y contacta con nosotros. Bienvenido a nuestra web.|Explora los productos AG|Descubre nuestro software y aplicaciones con enlaces para tus plataformas.|Conoce AG y las ideas detrás de nuestro trabajo.|¿Tienes una pregunta, idea u opinión? Nos gustaría escucharte.|Todos|No hay mensajes con este filtro.|Información del producto|Versión y estado',
de: 'Alles rund um AG, an einem Ort.|Entdecke AG-Produkte, lerne uns kennen und nimm Kontakt auf. Willkommen auf unserer Website.|AG-Produkte entdecken|Entdecke unsere Software und Apps mit Links für deine Plattformen.|Lerne AG und die Ideen hinter unserer Arbeit kennen.|Eine Frage, Idee oder Rückmeldung? Schreib uns gerne.|Alle|Keine Nachrichten für diesen Filter.|Produktinformationen|Version und Status',
sd: 'AG جي دنيا، هڪ ئي هنڌ.|AG جون شيون ڏسو، اسان بابت ڄاڻو ۽ رابطو ڪريو. اسان جي هوم سائيٽ تي ڀليڪار.|AG جون شيون ڏسو|اسان جا سافٽ ويئر ۽ ايپس پنهنجي پليٽ فارم جي لنڪن سان ڏسو.|AG ۽ اسان جي ڪم جي خيالن بابت ڄاڻو.|سوال، تجويز يا راءِ آهي؟ اسان کي پيغام موڪليو.|سڀ|هن فلٽر ۾ ڪو پيغام ناهي.|پروڊڪٽ جي ڄاڻ|ورزن ۽ حالت',
hnd: 'AG دی دنیا، ہکّو جگہ۔|AG دیاں مصنوعات ویکھو، ساڈے بارے جانو تے رابطہ کرو۔ ساڈی ہوم سائٹ تے جی آیاں۔|AG دیاں مصنوعات ویکھو|ساڈے سافٹ ویئر تے ایپس اپنے پلیٹ فارم دے لنک نال ویکھو۔|AG تے ساڈے کم دے خیالاں بارے جانو۔|سوال، تجویز یا رائے اے؟ سانوں پیغام بھیجو۔|سارے|ایس فلٹر وچ کوئی پیغام نئیں۔|پروڈکٹ دی معلومات|ورژن تے حالت',
skr: 'AG دی دنیا، ہک جاہ تے۔|AG دیاں مصنوعات ݙیکھو، ساݙے بارے ڄاڻو تے رابطہ کرو۔ ساݙی ہوم سائٹ تے ست بسم اللہ۔|AG دیاں مصنوعات ݙیکھو|ساݙے سافٹ ویئر تے ایپس اپݨے پلیٹ فارم دے لنک نال ݙیکھو۔|AG تے ساݙے کم دے خیالاں بارے ڄاڻو۔|سوال، تجویز یا رائے ہے؟ ساکوں پیغام بھیڄو۔|سارے|ایں فلٹر وچ کوئی پیغام کائنی۔|پروڈکٹ دی معلومات|ورژن تے حالت',
hi: 'AG की दुनिया, एक ही जगह।|AG के उत्पाद खोजें, हमारे बारे में जानें और संपर्क करें। हमारी वेबसाइट पर स्वागत है।|AG के उत्पाद देखें|हमारे सॉफ़्टवेयर और ऐप देखें, आपके प्लेटफ़ॉर्म के लिंक के साथ।|AG और हमारे काम के पीछे के विचारों को जानें।|कोई सवाल, विचार या सुझाव है? हमें संदेश भेजें।|सभी|इस फ़िल्टर में कोई संदेश नहीं है।|उत्पाद की जानकारी|संस्करण और स्थिति',
ur_roman: 'AG ki duniya, aik hi jagah.|AG ki products dekhein, hamare bare mein janein aur rabta karein. Hamari home site par khush aamdeed.|AG ki products dekhein|Hamare software aur apps apne platform ke links ke saath dekhein.|AG aur hamare kaam ke peeche ke khayalat janein.|Sawal, tajweez ya raye hai? Humein paigham bhejein.|Sab|Is filter mein koi paigham nahi.|Product ki maloomat|Version aur halat',
bn: 'AG-এর সবকিছু, এক জায়গায়।|AG-এর পণ্য দেখুন, আমাদের সম্পর্কে জানুন এবং যোগাযোগ করুন। আমাদের ওয়েবসাইটে স্বাগতম।|AG-এর পণ্য দেখুন|আপনার প্ল্যাটফর্মের লিঙ্কসহ আমাদের সফটওয়্যার ও অ্যাপ দেখুন।|AG এবং আমাদের কাজের পেছনের ভাবনাগুলো জানুন।|প্রশ্ন, ধারণা বা মতামত আছে? আমাদের বার্তা পাঠান।|সব|এই ফিল্টারে কোনো বার্তা নেই।|পণ্যের তথ্য|সংস্করণ ও অবস্থা',
ru: 'Всё об AG, в одном месте.|Откройте продукты AG, узнайте о нас и свяжитесь с нами. Добро пожаловать на наш сайт.|Откройте продукты AG|Посмотрите наши программы и приложения со ссылками для ваших платформ.|Узнайте об AG и идеях, стоящих за нашей работой.|Есть вопрос, идея или отзыв? Напишите нам.|Все|Нет сообщений для этого фильтра.|Информация о продукте|Версия и статус',
it: 'Tutto AG, in un unico posto.|Scopri i prodotti AG, conosci il nostro lavoro e contattaci. Benvenuto nel nostro sito.|Scopri i prodotti AG|Esplora software e app con i link per le tue piattaforme.|Conosci AG e le idee dietro il nostro lavoro.|Hai una domanda, un’idea o un commento? Scrivici.|Tutti|Nessun messaggio per questo filtro.|Informazioni sul prodotto|Versione e stato',
pt: 'Tudo sobre AG, num só lugar.|Explore os produtos AG, conheça-nos e entre em contato. Bem-vindo ao nosso site.|Explore os produtos AG|Descubra nossos programas e aplicativos com links para suas plataformas.|Conheça AG e as ideias por trás do nosso trabalho.|Tem uma pergunta, ideia ou opinião? Escreva-nos.|Todos|Nenhuma mensagem neste filtro.|Informações do produto|Versão e status',
ko: 'AG의 모든 것을 한곳에서.|AG 제품을 살펴보고, 우리에 대해 알아보고, 연락하세요. 웹사이트에 오신 것을 환영합니다.|AG 제품 살펴보기|사용하는 플랫폼의 링크와 함께 소프트웨어와 앱을 찾아보세요.|AG와 우리 작업의 바탕이 되는 아이디어를 알아보세요.|질문, 아이디어 또는 의견이 있나요? 알려주세요.|전체|이 필터에 해당하는 메시지가 없습니다.|제품 정보|버전 및 상태',
id: 'Semua tentang AG, di satu tempat.|Jelajahi produk AG, kenali kami dan hubungi kami. Selamat datang di situs kami.|Jelajahi produk AG|Temukan perangkat lunak dan aplikasi kami dengan tautan untuk platform Anda.|Kenali AG dan gagasan di balik karya kami.|Punya pertanyaan, ide atau masukan? Kirimkan pesan kepada kami.|Semua|Tidak ada pesan dalam filter ini.|Informasi produk|Versi dan status'
};
export const siteCopy = Object.fromEntries(Object.entries(rows).map(([lang, row]) => {
    const values = row.split('|');
    if (values.length !== keys.length) throw new Error('Incomplete site copy: ' + lang);
    return [lang, Object.fromEntries(keys.map((key, index) => [key, values[index]]))];
}));
const editorTitles = {
    en:'Add product|Edit product', ur:'پروڈکٹ شامل کریں|پروڈکٹ میں ترمیم کریں',
    ar:'إضافة منتج|تعديل المنتج', tr:'Ürün ekle|Ürünü düzenle', ja:'製品を追加|製品を編集', zh:'添加产品|编辑产品',
    pa:'پروڈکٹ شامل کرو|پروڈکٹ بدلّو', ps:'محصول زیات کړئ|محصول سم کړئ', bal:'پروڈکٹ شامل بکن|پروڈکٹ بدل بکن',
    fr:'Ajouter un produit|Modifier le produit', es:'Añadir producto|Editar producto', de:'Produkt hinzufügen|Produkt bearbeiten',
    sd:'پروڊڪٽ شامل ڪريو|پروڊڪٽ ۾ تبديلي ڪريو', hnd:'پروڈکٹ شامل کرو|پروڈکٹ بدلو', skr:'پروڈکٹ شامل کرو|پروڈکٹ وچ تبدیلی کرو',
    hi:'उत्पाद जोड़ें|उत्पाद संपादित करें', ur_roman:'Product shamil karein|Product mein tarmeem karein',
    bn:'পণ্য যোগ করুন|পণ্য সম্পাদনা করুন', ru:'Добавить продукт|Изменить продукт', it:'Aggiungi prodotto|Modifica prodotto',
    pt:'Adicionar produto|Editar produto', ko:'제품 추가|제품 수정', id:'Tambah produk|Edit produk'
};
for (const [lang, row] of Object.entries(editorTitles)) {
    const [add, edit] = row.split('|');
    Object.assign(siteCopy[lang], {'editor.addProduct':add, 'editor.editProduct':edit});
}
