import {t} from './localization.js';
import {watchOrganization,manageTeam,latestAssignment,ancestors,memberStatus,safeTeamURL} from './team-data.js';
import {element,button,dateText,nodeName} from './team-ui.js';
import {busy,toast,initValidation} from './ui.js';
let dispose;
export function initTeamManagement(rank){
    const host=document.getElementById('teamManagement'),link=document.getElementById('teamManagementLink');
    if(!host)return;const allowed=['OWNER','SUPER_ADMIN','ADMIN'].includes(rank);link.classList.toggle('hidden',!allowed);
    if(!allowed){dispose?.();dispose=null;host.replaceChildren();return;}if(dispose)return;
    let org,source,editingMember=null,editingNode=null,memberRevision,nodeRevision,uploadedAvatar='';
    host.className='team-management';
    const heading=element('h2','',t('team.title')),status=element('p','');status.setAttribute('role','status');
    const actions=element('div','team-actions'),list=element('div','team-admin-list'),nodeList=element('div','team-node-list');
    const memberDetails=element('details','team-editor'),memberSummary=element('summary','',t('org.profile')),memberForm=element('form','team-editor-form');memberForm.id='teamMemberForm';
    const nodeDetails=element('details','team-editor'),nodeSummary=element('summary','',t('org.organization')),nodeForm=element('form','team-editor-form');nodeForm.id='teamNodeForm';
    const memberFields={},nodeFields={};
    function field(form,fields,key,label,type='text',required=false,max=200){const wrapper=element('label','team-editor-field'),span=element('span','',t(label));span.dataset.i18n=label;const control=element(type==='textarea'?'textarea':type==='select'?'select':'input');if(type!=='textarea'&&type!=='select')control.type=type;control.id=`${form.id}-${key}`;control.name=key;control.required=required;if(type==='text'||type==='textarea')control.maxLength=max;wrapper.append(span,control);form.append(wrapper);fields[key]=control;return wrapper;}
    field(memberForm,memberFields,'name','details.name','text',true,150);field(memberForm,memberFields,'role','org.role');
    field(memberForm,memberFields,'startDate','org.joined','date',true);field(memberForm,memberFields,'status','org.history','select');
    memberFields.status.append(new Option(t('org.current'),'current'),new Option(t('org.former'),'former'));memberFields.status.options[0].dataset.i18n='org.current';memberFields.status.options[1].dataset.i18n='org.former';
    const endGroup=field(memberForm,memberFields,'endDate','org.left','date');
    field(memberForm,memberFields,'nodeId','org.team','select');
    const transferGroup=field(memberForm,memberFields,'transferDate','org.transferDate','date');
    field(memberForm,memberFields,'avatar','admin.imageURL','text',false,2048);field(memberForm,memberFields,'file','admin.upload','file');memberFields.file.accept='image/png,image/jpeg,image/webp';
    const preview=element('img','team-avatar-preview');preview.alt='';preview.hidden=true;memberForm.append(preview);
    field(memberForm,memberFields,'portfolio','team.portfolio','url',false,2048);field(memberForm,memberFields,'bio','details.description','textarea',false,8000);field(memberForm,memberFields,'skills','org.skills','textarea',false,1700);
    const historyNote=element('p','team-editor-note');historyNote.dataset.i18n='org.historyNote';historyNote.textContent=t('org.historyNote');memberForm.append(historyNote);
    const memberError=element('p','form-error');memberError.setAttribute('role','alert');const memberSave=button('admin.save',null,'primary-btn');memberSave.type='submit';memberForm.append(memberError,memberSave,button('btn.cancel',()=>memberDetails.open=false));
    field(nodeForm,nodeFields,'name','details.name','text',true,150);field(nodeForm,nodeFields,'type','org.organization','select');nodeFields.type.append(new Option(t('org.department'),'department'),new Option(t('org.team'),'team'));nodeFields.type.options[0].dataset.i18n='org.department';nodeFields.type.options[1].dataset.i18n='org.team';field(nodeForm,nodeFields,'parentId','org.parent','select',true);
    const nodeError=element('p','form-error');nodeError.setAttribute('role','alert');const nodeSave=button('admin.save',null,'primary-btn');nodeSave.type='submit';nodeForm.append(nodeError,nodeSave,button('btn.cancel',()=>nodeDetails.open=false));
    memberDetails.append(memberSummary,memberForm);nodeDetails.append(nodeSummary,nodeForm);
    actions.append(button('admin.add',()=>openMember()),button('org.organization',()=>openNode()));host.append(heading,status,actions,list,memberDetails,element('h3','',t('org.organization')),nodeList,nodeDetails);
    const today=new Date().toISOString().slice(0,10);for(const key of ['startDate','endDate','transferDate'])memberFields[key].max=today;
    function options(){if(!org)return;const nodeValue=memberFields.nodeId.value;memberFields.nodeId.replaceChildren(new Option(t('org.unspecified'),''));for(const node of org.nodes.filter(n=>n.id!=='ag'))memberFields.nodeId.append(new Option(ancestors(node.id,org.nodes).map(nodeName).join(' / '),node.id));memberFields.nodeId.value=nodeValue;
        const parentValue=nodeFields.parentId.value;nodeFields.parentId.replaceChildren();for(const node of org.nodes.filter(n=>!editingNode||!ancestors(n.id,org.nodes).some(parent=>parent.id===editingNode.id)))nodeFields.parentId.append(new Option(ancestors(node.id,org.nodes).map(nodeName).join(' / '),node.id));nodeFields.parentId.value=parentValue||'ag';}
    function dependent(){const former=memberFields.status.value==='former';endGroup.hidden=!former;memberFields.endDate.disabled=!former;memberFields.endDate.required=former;memberFields.endDate.min=memberFields.startDate.value;const transferred=Boolean(editingMember)&&memberFields.nodeId.value!==(latestAssignment(editingMember)?.nodeId||'');transferGroup.hidden=!transferred;memberFields.transferDate.required=transferred;memberFields.transferDate.disabled=!transferred;memberFields.transferDate.min=latestAssignment(editingMember)?.startDate||memberFields.startDate.value;}
    memberFields.status.onchange=dependent;memberFields.nodeId.onchange=dependent;memberFields.startDate.oninput=dependent;
    memberFields.avatar.oninput=()=>{uploadedAvatar=memberFields.avatar.value.trim();preview.src=safeTeamURL(uploadedAvatar,true)||'';preview.hidden=!preview.src;};
    memberFields.file.onchange=async()=>{try{const file=memberFields.file.files?.[0];if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>4000000)throw Error('org.imageError');const bitmap=await createImageBitmap(file),canvas=document.createElement('canvas'),ratio=Math.min(1,400/Math.max(bitmap.width,bitmap.height));canvas.width=Math.round(bitmap.width*ratio);canvas.height=Math.round(bitmap.height*ratio);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();uploadedAvatar=canvas.toDataURL('image/webp',.8);if(uploadedAvatar.length>160000)throw Error('org.imageError');memberFields.avatar.value='';preview.src=uploadedAvatar;preview.hidden=false;memberError.textContent='';}catch{uploadedAvatar=editingMember?.avatar||'';memberError.textContent=t('org.imageError');memberFields.file.value='';}};
    function openMember(member=null){editingMember=member;memberRevision=org.revision;memberForm.reset();memberError.textContent='';uploadedAvatar=member?.avatar||'';for(const key of ['name','role','startDate','endDate','portfolio','bio'])memberFields[key].value=member?.[key]||'';memberFields.startDate.readOnly=Boolean(member);memberFields.skills.value=member?.skills.join('\n')||'';memberFields.status.value=member?memberStatus(member):'current';memberFields.status.disabled=Boolean(member?.endDate);memberFields.avatar.value=uploadedAvatar.startsWith('data:')?'':uploadedAvatar;preview.hidden=!uploadedAvatar;preview.src=uploadedAvatar||'';options();memberFields.nodeId.value=latestAssignment(member||{})?.nodeId||'';memberFields.nodeId.disabled=Boolean(member?.endDate);dependent();memberDetails.open=true;memberDetails.scrollIntoView({block:'nearest'});memberFields.name.focus();}
    function openNode(node=null){editingNode=node;nodeRevision=org.revision;nodeForm.reset();nodeError.textContent='';nodeFields.name.value=node?.name||'';nodeFields.type.value=node?.type||'department';options();nodeFields.parentId.value=node?.parentId||'ag';nodeDetails.open=true;nodeFields.name.focus();}
    function errorMessage(error){const key=error.message?.replace(/^.*?(org\.[a-zA-Z]+).*$/,'$1');return key&&t(key)!==key?t(key):t('msg.error');}
    memberForm.onsubmit=event=>{event.preventDefault();busy(memberSave,async()=>{memberError.textContent='';try{const member={id:editingMember?.id||crypto.randomUUID(),name:memberFields.name.value.trim(),role:memberFields.role.value.trim(),startDate:memberFields.startDate.value,endDate:memberFields.status.value==='former'?memberFields.endDate.value:null,nodeId:memberFields.nodeId.value,transferDate:memberFields.transferDate.value,avatar:uploadedAvatar,portfolio:memberFields.portfolio.value.trim(),bio:memberFields.bio.value.trim(),skills:memberFields.skills.value.split(/\n|,/).map(s=>s.trim()).filter(Boolean)};await manageTeam(memberRevision,{kind:'member',member});memberDetails.open=false;toast(t('msg.success'));}catch(error){memberError.textContent=errorMessage(error);}});};
    nodeForm.onsubmit=event=>{event.preventDefault();busy(nodeSave,async()=>{nodeError.textContent='';try{await manageTeam(nodeRevision,{kind:'node',node:{id:editingNode?.id||crypto.randomUUID(),name:nodeFields.name.value.trim(),type:nodeFields.type.value,parentId:nodeFields.parentId.value}});nodeDetails.open=false;toast(t('msg.success'));}catch(error){nodeError.textContent=errorMessage(error);}});};
    function render(){if(!org)return;heading.textContent=t('team.title');status.textContent=source==='live'?'':source==='loading'?t('msg.loading'):source==='error'?t('auth.network'):t('org.initial');list.replaceChildren();for(const member of org.members){const row=element('div','team-admin-row');row.append(element('strong','',member.name),element('span','',`${dateText(member.startDate)} → ${dateText(member.endDate)}`),button('details.edit',()=>openMember(member)));list.append(row);}nodeList.replaceChildren();for(const node of org.nodes.filter(n=>n.id!=='ag')){const row=element('div','team-admin-row');row.append(element('span','',ancestors(node.id,org.nodes).map(nodeName).join(' / ')),button('details.edit',()=>openNode(node)));nodeList.append(row);}options();}
    dispose=watchOrganization((value,state)=>{org=value;source=state;render();});window.addEventListener('languageChanged',render);initValidation(host);
}

